# Generated by Django 3.2.25 on 2024-08-05 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('apartmentID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numberOfBedroom', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentOwner',
            fields=[
                ('apartmentOwnerID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('instructor', models.CharField(max_length=255)),
                ('duration', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('departmentName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=100)),
                ('active', models.BooleanField()),
                ('departmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('scheduleID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('time', models.DateTimeField()),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.customer')),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('recommendationID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5)),
                ('apartmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.apartment')),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('leadID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=255)),
                ('productType', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=100)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numberOfBedroom', models.CharField(max_length=50)),
                ('surroundingAmenities', models.TextField()),
                ('addition', models.TextField()),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeCourse',
            fields=[
                ('employeeCourseID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.course')),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInteraction',
            fields=[
                ('interactionID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('status', models.PositiveIntegerField()),
                ('updatedTime', models.DateTimeField()),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.customer')),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.employee')),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='apartmentOwnerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.apartmentowner'),
        ),
    ]
