# Generated by Django 3.2.25 on 2024-08-07 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20240808_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='createdBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.employee'),
            preserve_default=False,
        ),
    ]
